services:
  - type: web
    name: product-import-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
